### ISSUE TITLE
Fix error on folder/notebooks automatically updated via CI

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/awesome-notebooks#1209]
There is a error message I don't understand -> ModuleNotFoundError: No module named 'packaging'

URL : https://github.com/jupyter-naas/awesome-notebooks/actions/runs/3166609807/jobs/5156441106

Could you please have a look @Dr0p42 ?

**Comment by Dr0p42** [comment]
I just pushed a fix. It seems that it worked but I am waiting for Gitbook to sync again.

**Comment by Dr0p42** [comment]
It's fixed 🚀

**Comment by jravenel** [comment]
as discussed today, it seems broken still 
<img width="968" alt="Screenshot 2022-10-04 at 18 27 15" src="https://user-images.githubusercontent.com/21052349/193928107-5d6c73a4-c420-44a5-953b-f32516bf98da.png">

**Comment by jravenel** [comment]
Hey @Dr0p42 just a heads up on this as some of the folder are still missing their "+" feature to see the template under it.

**Comment by FlorentLvr** [comment]
@Dr0p42, @jravenel, is it fixed now? I am not sure to understand what's the issue. Can you explain a bit more?
